# Generated by Django 3.2.8 on 2021-10-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
