# Generated by Django 3.2 on 2022-01-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_author_image'),
        ('group', '0003_auto_20211028_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='group',
            name='describtion',
            field=models.CharField(default='Without Description', max_length=96),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='Groups'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='add-slug-all-groups', max_length=96),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=96, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.author'),
        ),
    ]
